name: Bug Report
description: Report a problem with the app.
title: "Bug: "
labels: [bug]
assignees:
  - rohankhayech
body:
  - type: textarea
    id: desc
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: steps
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior:
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: markdown
    attributes:
      value: "### Device and version info"
  - type: input
    id: device
    attributes:
      label: Device
      placeholder: Samsung Galaxy S25
    validation:
      required: true
  - type: input
    id: android
    attributes:
      label: Android Version
      description: "Found in your device's About settings page."
      placeholder: Android 16
    validation:
      required: true
  - type: input
    id: version
    attributes:
      label: App Version
      description: "Found in Choona's About settings page."
      placeholder: v1.5.1
    validation:
      required: true
  - type: input
    id: build-type
    attributes:
      label: Build Type
      description: "Found in Choona's About settings page."
      placeholder: Play Store / Open Source
    - type: input
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
