name: Submit Gradle Dependencies
on:
  push:
    branches:
      - main
      - ci/**
    paths:
      - '**.gradle'
      - '**.gradle.kts'
      - '**.versions.toml'
      - 'app/libs/**'
      - '.github/workflows/gradle-dependency-submission.yml'

permissions:
  contents: read
  id-token: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-submission@v4
