name: Submit Gradle Dependencies
on:
  push:
    branches:
      - main
    paths:
      - '**.gradle'
      - 'app/libs/**'
      - '.github/workflows/gradle-dependency-submission.yml'

jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run snapshot action
        uses: mikepenz/gradle-dependency-submission@v0.9.0
        with:
          gradle-build-module: ":app"
          gradle-build-configuration: |-
            debugCompileClasspath
